spring.application.name=biblioteca
#1. String connection.
spring.datasource.url=jdbc:sqlserver://DESKTOP-OKIQD9U:1433;databaseName=BiblitecaDBMDP2;encrypt=true;trustServerCertificate=true;loginTimeout=30;
#2. Credenciales
spring.datasource.username=sa
spring.datasource.password=Will423
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#3. Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl